### ISSUE TITLE
Bug with DateTimeFormatter in openjdk 11.0.7

### ISSUE THREAD

**Issue by iNomaD** [AdoptOpenJDK/openjdk-support#109]
* **Platform and architecture**: macOS 10.14.6

* **Java version (from "java --version")**: OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.7+10, mixed mode)

* **Have you tested it with other vendors' java**: tested and passed test on java 11.0.2 2019-01-15 LTS

* **Steps to reproduce**:
```
    @Test
    public void omgIsItABug() {
        String recordDate = "5/2/2019 1:2:3 AM";
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("M[M]/d[d]/yyyy h[h]:m[m]:s[s] a");
        LocalDateTime result = LocalDateTime.parse(recordDate, formatter);
        assertEquals(LocalDateTime.of(2019, 5, 2, 1, 2, 3), result);
    }
```

* **Error messsage and/or description of what is not working as expected**:
```
Text '5/2/2019 1:2:3 AM' could not be parsed at index 15
java.time.format.DateTimeParseException: Text '5/2/2019 1:2:3 AM' could not be parsed at index 15
	at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2046)
	at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1948)
	at java.base/java.time.LocalDateTime.parse(LocalDateTime.java:492)
```

**Comment by aahlenst** [comment]
@jerboaa Another one to report. Would you be so kind?

Reproducer: https://github.com/aahlenst/datetimeformatter-parse-bug

Happens with AdoptOpenJDK 11.0.7 as well as Azul Zulu 11.0.7 on macOS 10.15.4. It does not happen with 11.0.7 on Linux. So it's specific to macOS. Haven't found any match in JBS.

Linux:
```
$ uname -a
Linux 26d2664492d3 4.19.76-linuxkit #1 SMP Tue May 26 11:42:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
$ java -version
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.7+10, mixed mode)
$ ./gradlew --console=plain --no-daemon clean test
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/6.4.1/userguide/gradle_daemon.html.
Daemon will be stopped at the end of the build stopping after processing
> Task :clean
> Task :compileJava NO-SOURCE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE
> Task :compileTestJava
> Task :processTestResources NO-SOURCE
> Task :testClasses
> Task :test

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.4.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 4s
3 actionable tasks: 3 executed
```

macOS 10.15.4, first with AdoptOpenJDK:

```
$ uname -a
Darwin blackbird 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64
$ java -version                                   
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.7+10, mixed mode)
$ ./gradlew --console=plain --no-daemon clean test
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/6.4.1/userguide/gradle_daemon.html.
Daemon will be stopped at the end of the build stopping after processing
> Task :clean
> Task :compileJava NO-SOURCE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE
> Task :compileTestJava
> Task :processTestResources NO-SOURCE
> Task :testClasses

> Task :test FAILED

net.adoptopenjdk.DateFormatterTest > parsePattern FAILED
    java.time.format.DateTimeParseException at DateFormatterTest.java:15

1 test completed, 1 failed

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///Users/andreas/Documents/AdoptOpenJDK/reproducer-109/build/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.4.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 3s
3 actionable tasks: 3 executed
```

Now with Azul Zulu:

```
$ uname -a
Darwin blackbird 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64
$ java -version                                   
openjdk version "11.0.7" 2020-04-14 LTS
OpenJDK Runtime Environment Zulu11.39+15-CA (build 11.0.7+10-LTS)
OpenJDK 64-Bit Server VM Zulu11.39+15-CA (build 11.0.7+10-LTS, mixed mode)
$ ./gradlew --console=plain --no-daemon clean test
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/6.4.1/userguide/gradle_daemon.html.
Daemon will be stopped at the end of the build stopping after processing
> Task :clean
> Task :compileJava NO-SOURCE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE
> Task :compileTestJava
> Task :processTestResources NO-SOURCE
> Task :testClasses

> Task :test FAILED

net.adoptopenjdk.DateFormatterTest > parsePattern FAILED
    java.time.format.DateTimeParseException at DateFormatterTest.java:15

1 test completed, 1 failed

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///Users/andreas/Documents/AdoptOpenJDK/reproducer-109/build/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.4.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 4s
3 actionable tasks: 3 executed
```

**Comment by aahlenst** [comment]
Still happening with 11.0.8 and reported.

**Comment by aahlenst** [comment]
https://bugs.openjdk.java.net/browse/JDK-8250626

**Comment by aahlenst** [comment]
@iNomaD If you do not agree with the upstream resolution, https://bugs.java.com/bugdatabase/faq.do#faq-6 explains how you can comment on the issue yourself.
