### ISSUE TITLE
JAOTC Compile .so with Spring Boot jar AdoptOpenJDK (build 10.0.2+13)

### ISSUE THREAD

**Issue by kk60195** [AdoptOpenJDK/openjdk-support#119]
* **Platform and architecture (e.g. Linux/x64**:
Mac:
Darwin computer 18.7.0 Darwin Kernel Version 18.7.0: Mon Apr 27 20:09:39 PDT 2020; root:xnu-4903.278.35~1/RELEASE_X86_64 x86_64

* **Java version (from "java --version") e.g. 1.8.0_181, 11.0.4+11 etc.**:
openjdk 10.0.2 2018-07-17
OpenJDK Runtime Environment AdoptOpenJDK (build 10.0.2+13)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 10.0.2+13, mixed mode)
* **Variant e.g. HotSpot or OpenJ9**:

* **Have you tested it with other vendors' java**:
Dragonwell from alibaba

* **Steps to reproduce**:
* Create a basic Spring boot application with only one endpoint. (https://github.com/bzdgn/docker-spring-boot-java-web-service-example/blob/master/README.md) 
* Maven clean install
* see a Jar file is created under a Target folder
* jaotc --output test.so --jar target/docker-java-app-example.jar    

 **Error messsage and/or description of what is not working as expected**:

jaotc --output test.so --jar target/docker-java-app-example.jar                                                                                                                                                                                 
Exception in thread "main" java.lang.NoClassDefFoundError: com/levo/dockerexample/DockerApp (wrong name: BOOT-INF/classes/com/levo/dockerexample/DockerApp)
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1009)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
        at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:545)
        at java.base/java.net.URLClassLoader.access$100(URLClassLoader.java:83)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:453)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:447)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:446)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:566)
        at java.base/java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:890)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
        at jdk.aot/jdk.tools.jaotc.collect.ClassSearch.loadClass(ClassSearch.java:56)
        at jdk.aot/jdk.tools.jaotc.collect.ClassSearch.lambda$search$0(ClassSearch.java:48)
        at jdk.aot/jdk.tools.jaotc.collect.jar.JarFileSource.eachClass(JarFileSource.java:48)
        at jdk.aot/jdk.tools.jaotc.collect.ClassSearch.search(ClassSearch.java:48)
        at jdk.aot/jdk.tools.jaotc.Collector.collectClassesToCompile(Collector.java:64)
        at jdk.aot/jdk.tools.jaotc.Main.run(Main.java:134)
        at jdk.aot/jdk.tools.jaotc.Main.run(Main.java:101)
        at jdk.aot/jdk.tools.jaotc.Main.main(Main.java:80)

Expecting a .so file when i pass in a spring boot jar. Is there a way i can get this to work?
[docker-spring-boot-java-web-service-example-master.zip](https://github.com/AdoptOpenJDK/openjdk-support/files/4724303/docker-spring-boot-java-web-service-example-master.zip)

**Comment by karianna** [comment]
Please try with 11.0.7+10 - The 10.x.x series is no longer supported.

**Comment by kk60195** [comment]
thank you for your response. Unfortunately it is the same issue. 
Does jaotc not deal with maven spring structures well?

Output:

jaotc --output test.so --jar target/docker-java-app-example.jar                                                                                                                                                                                 
Error: java.lang.NoClassDefFoundError: com/levo/dockerexample/DockerApp (wrong name: BOOT-INF/classes/com/levo/dockerexample/DockerApp)
java.lang.NullPointerException
        at jdk.aot@11.0.7/jdk.tools.jaotc.Main.run(Main.java:166)
        at jdk.aot@11.0.7/jdk.tools.jaotc.Main.run(Main.java:132)
        at jdk.aot@11.0.7/jdk.tools.jaotc.Main.main(Main.java:88)

**Comment by karianna** [comment]
Did this also fail with Dragonwell

**Comment by kk60195** [comment]
my mistake on the dragonwell info. I was testing jwarmup on it. But this error also appears when i do a docker of 9 10 and 11 of adoptopenjdk

**Comment by kk60195** [comment]
is jaotc not meant to pass in spring boot jars?

**Comment by aahlenst** [comment]
jaotc and Spring aren't a natural fit if you look at the [JEP 295: Ahead-of-Time Compilation](https://openjdk.java.net/jeps/295), especially the section about limitations. Spring makes heavy use of dynamic proxies. It should be possible to use Spring and jaotc if you only compile to boot classpath, see https://github.com/dsyer/spring-boot-java-10#ahead-of-time-compilation-aot. What you're doing above is not supposed to work.

**Comment by karianna** [comment]
FYI - Spring does support Graal Native image (it is actively adding support for this), so I'd try looking at that.

**Comment by aahlenst** [comment]
With Graal https://github.com/spring-projects-experimental/spring-fu might be helpful.
