### ISSUE TITLE
jdk15 ea: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty

### ISSUE THREAD

**Issue by Siedlerchr** [AdoptOpenJDK/openjdk-support#181]
java-version: 15
    release_type: ea
    java-package: jdk
    openjdk_impl: hotspot
    architecture: x64
    release: latest

## Summary

I am using the latest version of Adotpopenjdk15 ea. Since a few days the gradle build fails downloading gradle version 6.3 due to a Runtime Exception. Previouly it was working fine.
```
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)
Caused by: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
	at java.base/sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:101)
	at java.base/sun.security.validator.Validator.getInstance(Validator.java:181)
	at java.base/sun.security.ssl.X509TrustManagerImpl.getValidator(X509TrustManagerImpl.java:309)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrustedInit(X509TrustManagerImpl.java:183)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:198)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:629)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:464)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:360)
	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:458)
	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:199)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:171)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1488)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1394)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:441)
	... 14 more
Caused by: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
	at java.base/java.security.cert.PKIXParameters.setTrustAnchors(PKIXParameters.java:200)
	at java.base/java.security.cert.PKIXParameters.<init>(PKIXParameters.java:120)
	at java.base/java.security.cert.PKIXBuilderParameters.<init>(PKIXBuilderParameters.java:104)
	at java.base/sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:98)

```

## Steps to reproduce
compile a java project with ea15 and gradlew 3.6

## Expected results

It works

## Triaging info

Java version:
ea15 latests

What is your operating system and platform?

Fails on all plattforms. Windows, linux, mac

How did you install Java?

Did it work before?

Did you test with other Java versions?
jdk 14 works.

**Comment by aahlenst** [comment]
Confirmed. Thank you for reporting this. We were about to start the release build.

**Comment by aahlenst** [comment]
Fixed builds:
* Linux: https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk15u/job/jdk15u-linux-x64-hotspot/35/
* macOS: https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk15u/job/jdk15u-mac-x64-hotspot/35/

**Comment by sxa** [comment]
@Siedlerchr Please reopen if the error occurs but I tested the new nightly buid from jenkins and it does not fail with the same error. Thanks for reporting this as it has allowed us to resolve it before the JDK15 GA 👍🏻

**Comment by Siedlerchr** [comment]
Thanks for the quick fix! The current latest works again
