### ISSUE TITLE
java.security.NoSuchAlgorithmException: Could not create cipher AES/256

### ISSUE THREAD

**Issue by katarya** [AdoptOpenJDK/openjdk-support#195]
I am testing on 8u265b01, both on J9 and hotspot and get the same error. I don't see this error on Oracle JDK,
Exception stack:
Caused by: javax.net.ssl.SSLException: Algorithm missing:  
    at sun.security.ssl.SSLSocketImpl.changeWriteCiphers(SSLSocketImpl.java:2160)
    at sun.security.ssl.Handshaker.sendChangeCipherSpec(Handshaker.java:1190)
    at sun.security.ssl.ClientHandshaker.sendChangeCipherAndFinish(ClientHandshaker.java:1323)
    at sun.security.ssl.ClientHandshaker.serverHelloDone(ClientHandshaker.java:1233)
    at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:372)
    at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1082)
    at sun.security.ssl.Handshaker.process_record(Handshaker.java:1010)
    at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1079)
    at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1388)
    at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1416)
    at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1400)
    at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:394)
    at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:353)
    at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
    at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
    at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
    at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
    at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
    at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
    at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
    at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
    at com.hli.util.HttpClientUtil.execute(HttpClientUtil.java:42)
    at com.hli.le.connect.db.WrapperLESAConnection.initialize(WrapperLESAConnection.java:55)
    ... 10 more
Caused by: java.security.NoSuchAlgorithmException: Could not create cipher AES/256
    at sun.security.ssl.CipherBox.<init>(CipherBox.java:245)
    at sun.security.ssl.CipherBox.newCipherBox(CipherBox.java:263)
    at sun.security.ssl.CipherSuite$BulkCipher.newCipher(CipherSuite.java:519)
    at sun.security.ssl.Handshaker.newWriteCipher(Handshaker.java:882)
    at sun.security.ssl.SSLSocketImpl.changeWriteCiphers(SSLSocketImpl.java:2156)

**Comment by aahlenst** [comment]
Thanks for getting in touch, but as it stands, you do not provide enough information to diagnose the problem. Please share a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by katarya** [comment]
Why would this exception ( java.security.NoSuchAlgorithmException: Could not create cipher AES/256) be thrown? Is this algorithm not part of JCE ?

**Comment by aahlenst** [comment]
Provide a minimal code sample if you want help. Trying to diagnose issues without code always turns into a wild goose chase.

**Comment by aahlenst** [comment]
Closing due to lack of requested feedback. We're happy to reopen the issue if feedback is provided by the OP (or anybody else) at a later date.
