### ISSUE TITLE
Files.readAttributes()  will throw exception

### ISSUE THREAD

**Issue by forsmpa** [AdoptOpenJDK/openjdk-support#247]
## Summary

On Windows 10 a call of _Files.readAttributes(path, "owner:*", LinkOption.NOFOLLOW_LINKS)_  in the special case where the _path_ is located on Windows Subsystem Linux 2 mapped network drive. will produce exception.

_java.nio.file.FileSystemException: U:\path_to_file\filename.ext: Incorrect function._

This case is related to Maven builds not running as expected as with the case descriptions here https://github.com/codehaus-plexus/plexus-io/issues/36

## Steps to reproduce

A call with _path.getFileSystem()_ returns object of type
sun.nio.fs.WindowsFileSystem

A call with _path.getFileSystem().supportedFileAttributeViews()_ returns 
[owner, dos, acl, basic, user]

A call to _Files.readAttributes( path, "basic:*", LinkOption.NOFOLLOW_LINKS)_ returns
{
	lastAccessTime=2021-01-26T12:37:41.11Z, 
	lastModifiedTime=2021-01-26T12:37:41.12Z, 
	size=2085, 
	creationTime=2021-01-26T12:37:41.11Z, 
	isSymbolicLink=false, 
	isRegularFile=true, 
	fileKey=null, 
	isOther=false, 
	isDirectory=false
}

When expecting that file ownership information is available running call _Files.readAttributes(path, "owner:*", LinkOption.NOFOLLOW_LINKS)_  will produce exception.

_java.nio.file.FileSystemException: U:\path_to_file\filename.ext: Incorrect function._

## Expected results

I would expect this to return _null_ or more subtle way. This case 

## Actual results

_java.nio.file.FileSystemException: U:\path_to_file\filename.ext: Incorrect function._

## Triaging info

Java version:

openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
OpenJDK Client VM AdoptOpenJDK (build 11.0.10+9, mixed mode)

What is your operating system and platform?

Windows 10 Enterprise 2004 on x86-64

How did you install Java?

Unzipped zip file.

Did you test with other Java versions?

Tested with a little bit older AdoptOpenJDK 10.0.9.1+9 and results are the same.

**Comment by aahlenst** [comment]
@karianna Do you want to handle this internally?

**Comment by aahlenst** [comment]
@forsmpa Can you please create a small runnable test case (main class) that reproduces the problem? Reduces problems due to ambiguities.

**Comment by forsmpa** [comment]
```
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.LinkOption;
import java.nio.file.Path;

public class Example {
    public static void main(String[] args) throws IOException {
        String wslPath = "U:\\path\\to\\wsl2\\mapped\\network\\drive\\file.ext";
        File file = new File(wslPath);
        Path path = file.toPath();

        Files.readAttributes(path, "owner:*", LinkOption.NOFOLLOW_LINKS);  // Throws Exception
    }
}

```
...will result in...

```
Exception in thread "main" java.nio.file.FileSystemException: U:\path\\to\wsl2\mapped\network\drive\file.ext: Incorrect function.

	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:96)
	at java.base/sun.nio.fs.WindowsAclFileAttributeView.getFileSecurity(WindowsAclFileAttributeView.java:88)
	at java.base/sun.nio.fs.WindowsAclFileAttributeView.getOwner(WindowsAclFileAttributeView.java:121)
	at java.base/sun.nio.fs.FileOwnerAttributeViewImpl.getOwner(FileOwnerAttributeViewImpl.java:91)
	at java.base/sun.nio.fs.FileOwnerAttributeViewImpl.readAttributes(FileOwnerAttributeViewImpl.java:77)
	at java.base/sun.nio.fs.AbstractFileSystemProvider.readAttributes(AbstractFileSystemProvider.java:94)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1997)
	at Example.main(Example.java:13)

```

**Comment by michael-o** [comment]
https://bugs.openjdk.java.net/browse/JDK-8259617

**Comment by famod** [comment]
Not sure this is the right place to chime in (or that openjdk jira) but I'm seeing a very similar problem:
```
[...]
Caused by: java.io.IOException: java.security.PrivilegedActionException: java.nio.file.FileSystemException: U:\home\moldowan\.m2\repository\io\quarkus\quarkus-core\2.2.3.Final\quarkus-core-2.2.3.Final.jar: Unzulässige Funktion
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.initOwner(ZipFileSystem.java:254)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:148)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getZipFileSystem(ZipFileSystemProvider.java:125)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:120)
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:527)
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:399)
	at io.quarkus.runtime.util.ClassPathUtils.readStream(ClassPathUtils.java:196)
	at io.quarkus.runtime.util.ClassPathUtils.consumeStream(ClassPathUtils.java:159)
	at io.quarkus.runtime.util.ClassPathUtils.consumeAsStreams(ClassPathUtils.java:53)
	at io.quarkus.deployment.util.ServiceUtil.classNamesNamedIn(ServiceUtil.java:36)
	at io.quarkus.deployment.util.ServiceUtil.classesNamedIn(ServiceUtil.java:28)
	at io.quarkus.deployment.ExtensionLoader.loadStepsFrom(ExtensionLoader.java:133)
	at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:104)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:413)
	... 44 more
Caused by: java.security.PrivilegedActionException: java.nio.file.FileSystemException: U:\home\moldowan\.m2\repository\io\quarkus\quarkus-core\2.2.3.Final\quarkus-core-2.2.3.Final.jar: Unzulässige Funktion
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:558)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.initOwner(ZipFileSystem.java:245)
	... 57 more
Caused by: java.nio.file.FileSystemException: U:\home\moldowan\.m2\repository\io\quarkus\quarkus-core\2.2.3.Final\quarkus-core-2.2.3.Final.jar: Unzulässige Funktion
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:96)
	at java.base/sun.nio.fs.WindowsAclFileAttributeView.getFileSecurity(WindowsAclFileAttributeView.java:88)
	at java.base/sun.nio.fs.WindowsAclFileAttributeView.getOwner(WindowsAclFileAttributeView.java:121)
	at java.base/sun.nio.fs.FileOwnerAttributeViewImpl.getOwner(FileOwnerAttributeViewImpl.java:91)
	at java.base/java.nio.file.Files.getOwner(Files.java:2194)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.lambda$initOwner$2(ZipFileSystem.java:244)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:554)
	... 58 more
```

This is from a `QuarkusTest` running in Eclipse (which is running on Windows) from a mapped WSL2 network drive.

<details><summary>Full trace</summary>
<p>

```
java.lang.RuntimeException: java.lang.RuntimeException: java.io.IOException: java.security.PrivilegedActionException: java.nio.file.FileSystemException: U:\home\moldowan\.m2\repository\io\quarkus\quarkus-core\2.2.3.Final\quarkus-core-2.2.3.Final.jar: Unzulässige Funktion
	at io.quarkus.test.junit.QuarkusTestExtension.throwBootFailureException(QuarkusTestExtension.java:737)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestClassConstructor(QuarkusTestExtension.java:810)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.api.extension.InvocationInterceptor.interceptTestClassConstructor(InvocationInterceptor.java:72)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:77)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeTestClassConstructor(ClassBasedTestDescriptor.java:342)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateTestClass(ClassBasedTestDescriptor.java:289)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.instantiateTestClass(ClassTestDescriptor.java:79)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateAndPostProcessTestInstance(ClassBasedTestDescriptor.java:267)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$2(ClassBasedTestDescriptor.java:259)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$3(ClassBasedTestDescriptor.java:258)
	at org.junit.jupiter.engine.execution.TestInstancesProvider.getTestInstances(TestInstancesProvider.java:31)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$prepare$0(TestMethodTestDescriptor.java:101)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:100)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:65)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$prepare$1(NodeTestTask.java:111)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.prepare(NodeTestTask.java:111)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:79)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:84)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.run(JUnit5TestReference.java:98)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: java.lang.RuntimeException: java.io.IOException: java.security.PrivilegedActionException: java.nio.file.FileSystemException: U:\home\moldowan\.m2\repository\io\quarkus\quarkus-core\2.2.3.Final\quarkus-core-2.2.3.Final.jar: Unzulässige Funktion
	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:415)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:275)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:66)
	at io.quarkus.test.junit.QuarkusTestExtension.doJavaStart(QuarkusTestExtension.java:366)
	at io.quarkus.test.junit.QuarkusTestExtension.ensureStarted(QuarkusTestExtension.java:705)
	at io.quarkus.test.junit.QuarkusTestExtension.beforeAll(QuarkusTestExtension.java:752)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllCallbacks$8(ClassBasedTestDescriptor.java:368)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllCallbacks(ClassBasedTestDescriptor.java:368)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:192)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:78)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:136)
	... 33 more
Caused by: java.io.IOException: java.security.PrivilegedActionException: java.nio.file.FileSystemException: U:\home\moldowan\.m2\repository\io\quarkus\quarkus-core\2.2.3.Final\quarkus-core-2.2.3.Final.jar: Unzulässige Funktion
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.initOwner(ZipFileSystem.java:254)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:148)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getZipFileSystem(ZipFileSystemProvider.java:125)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:120)
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:527)
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:399)
	at io.quarkus.runtime.util.ClassPathUtils.readStream(ClassPathUtils.java:196)
	at io.quarkus.runtime.util.ClassPathUtils.consumeStream(ClassPathUtils.java:159)
	at io.quarkus.runtime.util.ClassPathUtils.consumeAsStreams(ClassPathUtils.java:53)
	at io.quarkus.deployment.util.ServiceUtil.classNamesNamedIn(ServiceUtil.java:36)
	at io.quarkus.deployment.util.ServiceUtil.classesNamedIn(ServiceUtil.java:28)
	at io.quarkus.deployment.ExtensionLoader.loadStepsFrom(ExtensionLoader.java:133)
	at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:104)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:413)
	... 44 more
Caused by: java.security.PrivilegedActionException: java.nio.file.FileSystemException: U:\home\moldowan\.m2\repository\io\quarkus\quarkus-core\2.2.3.Final\quarkus-core-2.2.3.Final.jar: Unzulässige Funktion
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:558)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.initOwner(ZipFileSystem.java:245)
	... 57 more
Caused by: java.nio.file.FileSystemException: U:\home\moldowan\.m2\repository\io\quarkus\quarkus-core\2.2.3.Final\quarkus-core-2.2.3.Final.jar: Unzulässige Funktion
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:96)
	at java.base/sun.nio.fs.WindowsAclFileAttributeView.getFileSecurity(WindowsAclFileAttributeView.java:88)
	at java.base/sun.nio.fs.WindowsAclFileAttributeView.getOwner(WindowsAclFileAttributeView.java:121)
	at java.base/sun.nio.fs.FileOwnerAttributeViewImpl.getOwner(FileOwnerAttributeViewImpl.java:91)
	at java.base/java.nio.file.Files.getOwner(Files.java:2194)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.lambda$initOwner$2(ZipFileSystem.java:244)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:554)
	... 58 more
```

</p>
</details>

**Comment by karianna** [comment]
Bug still open upstream

**Comment by karianna** [comment]
Bug still open upstream

**Comment by michael-o** [comment]
https://issues.apache.org/jira/browse/MJAR-273
