### ISSUE TITLE
NoClassDefFoundError happened when use  spring boot 2.2.6 

### ISSUE THREAD

**Issue by Xarrow** [AdoptOpenJDK/openjdk-support#89]
`ValueExtractorManager` NoClassDefFoundError happened when use spring boot 2.2.6 . But work well with oracle jdk and zulu jdk.

* platform : Windows 10 x64

* jdk info 

```
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_242-b08)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.242-b08, mixed mode)
```
* variant : hotspot
* test with other verdors :  oracle jdk , zulu jdk

* just simple example with spring boot,

Log in detail as below ,

```
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-04-21 12:11:38.522 ERROR 19280 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'defaultValidator' defined in class path resource [org/springframework/boot/autoconfigure/validation/ValidationAutoConfiguration.class]: Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: Could not initialize class org.hibernate.validator.internal.engine.valueextraction.ValueExtractorManager
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:882) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) ~[spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:140) [spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at org.github.helixcs.myspringboot.examples.c5.redis.JwtAppBootstrap.main(JwtAppBootstrap.java:18) [classes/:na]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.hibernate.validator.internal.engine.valueextraction.ValueExtractorManager
	at org.hibernate.validator.internal.engine.ValidatorFactoryImpl.<init>(ValidatorFactoryImpl.java:140) ~[hibernate-validator-6.0.18.Final.jar:6.0.18.Final]
	at org.hibernate.validator.HibernateValidator.buildValidatorFactory(HibernateValidator.java:38) ~[hibernate-validator-6.0.18.Final.jar:6.0.18.Final]
	at org.hibernate.validator.internal.engine.ConfigurationImpl.buildValidatorFactory(ConfigurationImpl.java:364) ~[hibernate-validator-6.0.18.Final.jar:6.0.18.Final]
	at org.springframework.validation.beanvalidation.LocalValidatorFactoryBean.afterPropertiesSet(LocalValidatorFactoryBean.java:310) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1855) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1792) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	... 15 common frames omitted
```

**Comment by aahlenst** [comment]
I ran the full test suite of Spring Boot 2.2.6 with AdoptOpenJDK 8u242 on Windows 10. Everything's green. Please provide a minimal sample that reproduces the problem **and that we can run** (e.g. sample project on GitHub).

**Comment by karianna** [comment]
Also, try 8u252 (just released)

**Comment by ant-druha** [comment]
Sample project is attached. Happens with `adopt-openjdk-1.8.0_282`.
[configuration-backend.zip](https://github.com/AdoptOpenJDK/openjdk-support/files/6076546/configuration-backend.zip)
[output.txt](https://github.com/AdoptOpenJDK/openjdk-support/files/6076547/output.txt)

**Comment by aahlenst** [comment]
@ant-druha Your project starts without problems on my machine. Furthermore, `org.hibernate.validator.internal.engine.valueextraction.ValueExtractorManager` is not part of the JDK, but Hibernate Validation. So it's unclear why you blame the JDK.

**Comment by ant-druha** [comment]
>So it's unclear why you blame the JDK.

Because it fails with this error only when running under this JDK. And works with others JDKs.

**Comment by aahlenst** [comment]
`mvn spring-boot:run` works for me. You're launching through IntelliJ, so maybe something goes wrong when declaring the classpath.

**Comment by ant-druha** [comment]
I do not understand then why the same classpath is working with any other 1.8 JDKs.

**Comment by ant-druha** [comment]
Thank you for checking. Hmm. It works for me with all other 1.8 JDK, including Zulu and Liberica except AdoptOpenJDK though.

**Comment by anste** [comment]
@ant-druha did you find any fix for this issue? I'm facing this one, too. Except I am using Spring-Boot 2.2.2 and the project works on Oracle and Corretto JVM. The error occurs in a deployed version of the project.

**Comment by Raytheon-Skywalker** [comment]
> Thank you for checking. Hmm. It works for me with all other 1.8 JDK, including Zulu and Liberica except AdoptOpenJDK though.

### Also got the same issue when using AdoptOpenJDK1.8.  It works as normal when I change to Oracle JDK1.8/Corretto-1.8.

**Comment by windstar20** [comment]
I solved the same problem by replacing it with oracle jdk 1.8.
Install the oracle jdk.

**Comment by cmoisei** [comment]
Why was this marked invalid? 

I am getting in an environment that is locked down with a Security manager, not saying that the presence of the Security Manager does it but I get the same stack YET I can't reproduce it in a similar, local, environment that is not locked. Runs as standalone boot app and as app deployed on a local tomcat.

It's on openjdk8 but will upgrade to openjdk11 - there is no other trace/exception !

**Comment by karianna** [comment]
> Why was this marked invalid?
> 
> I am getting in an environment that is locked down with a Security manager, not saying that the presence of the Security Manager does it but I get the same stack YET I can't reproduce it in a similar, local, environment that is not locked. Runs as standalone boot app and as app deployed on a local tomcat.
> 
> It's on openjdk8 but will upgrade to openjdk11 - there is no other trace/exception !

See the various comments above, upgrading to latest Adopt binaries solved the issue for various users.

**Comment by cmoisei** [comment]
> > Why was this marked invalid?
> > I am getting in an environment that is locked down with a Security manager, not saying that the presence of the Security Manager does it but I get the same stack YET I can't reproduce it in a similar, local, environment that is not locked. Runs as standalone boot app and as app deployed on a local tomcat.
> > It's on openjdk8 but will upgrade to openjdk11 - there is no other trace/exception !
> 
> See the various comments above, upgrading to latest Adopt binaries solved the issue for various users.

Yes, I saw all of that but just curious what is happening, the underlying case in important, no errors, no traces, no info. the class cannot be created. I have openjdk8, one of the latest, I will what happens when move to 11 today.

**Comment by cmoisei** [comment]
OK, so this issue is not invalid nor springboot related

What happens is when hibernate gets to be register as the JPA implementation and when a security manager is set, that class, ValueExtractorManager, would not get initialized and it would result in a weird exception that never seems to get logged or fired during the class defintion/creation

```
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.hibernate.validator.internal.engine.valueextraction.ValueExtractorManager
	at org.hibernate.validator.internal.engine.ValidatorFactoryImpl.<init>(ValidatorFactoryImpl.java:173) ~[hibernate-validator-6.2.0.Final.jar:6.2.0.Final]
	at org.hibernate.validator.HibernateValidator.buildValidatorFactory(HibernateValidator.java:38) ~[hibernate-validator-6.2.0.Final.jar:6.2.0.Final]
	at org.hibernate.validator.internal.engine.AbstractConfigurationImpl.buildValidatorFactory(AbstractConfigurationImpl.java:451) ~[hibernate-validator-6.2.0.Final.jar:6.2.0.Final]
	at javax.validation.Validation.buildDefaultValidatorFactory(Validation.java:103) ~[jakarta.validation-api-2.0.2.jar:?]
	at org.hibernate.cfg.beanvalidation.TypeSafeActivator.getValidatorFactory(TypeSafeActivator.java:502) ~[hibernate-core-5.4.32.Final.jar:5.4.32.Final]
	at org.hibernate.cfg.beanvalidation.TypeSafeActivator.activate(TypeSafeActivator.java:84) ~[hibernate-core-5.4.32.Final.jar:5.4.32.Final]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.hibernate.cfg.beanvalidation.BeanValidationIntegrator.integrate(BeanValidationIntegrator.java:131) ~[hibernate-core-5.4.32.Final.jar:5.4.32.Final]
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:283) ~[hibernate-core-5.4.32.Final.jar:5.4.32.Final]
	at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:468) ~[hibernate-core-5.4.32.Final.jar:5.4.32.Final]
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1259) ~[hibernate-core-5.4.32.Final.jar:5.4.32.Final]
	at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:58) ~[spring-orm-5.3.8.jar:5.3.8]
```

Adding this permission
("java.util.PropertyPermission" "org.hibernate.validator.force-disable-javafx-integration" "read")

or a wildcard "org.hibernate.*" should fix it.

Now, not a lot of tests are performed with the security manager enabled and lots of teams don't even bother to enable it ...

Hope this would help someone, one day!

**Comment by AgingChan** [comment]
@cmoisei Hi, we are facing the same issue on Azul JDK. Was wondering how to add the permission as you mentioned in your post when we start a spring boot application?

**Comment by cmoisei** [comment]
You can add them in the policy file that you specified at startup - that if
you run with a security manager.

**Comment by cdorn** [comment]
> OK, so this issue is not invalid nor springboot related
> 
> What happens is when hibernate gets to be register as the JPA implementation and when a security manager is set, that class, ValueExtractorManager, would not get initialized and it would result in a weird exception that never seems to get logged or fired during the class defintion/creation
> 
> ```
> Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.hibernate.validator.internal.engine.valueextraction.ValueExtractorManager
> 	at org.hibernate.validator.internal.engine.ValidatorFactoryImpl.<init>(ValidatorFactoryImpl.java:173) ~[hibernate-validator-6.2.0.Final.jar:6.2.0.Final]
> 	at org.hibernate.validator.HibernateValidator.buildValidatorFactory(HibernateValidator.java:38) ~[hibernate-validator-6.2.0.Final.jar:6.2.0.Final]
> 	at org.hibernate.validator.internal.engine.AbstractConfigurationImpl.buildValidatorFactory(AbstractConfigurationImpl.java:451) ~[hibernate-validator-6.2.0.Final.jar:6.2.0.Final]
> 	at javax.validation.Validation.buildDefaultValidatorFactory(Validation.java:103) ~[jakarta.validation-api-2.0.2.jar:?]
> 	at org.hibernate.cfg.beanvalidation.TypeSafeActivator.getValidatorFactory(TypeSafeActivator.java:502) ~[hibernate-core-5.4.32.Final.jar:5.4.32.Final]
> 	at org.hibernate.cfg.beanvalidation.TypeSafeActivator.activate(TypeSafeActivator.java:84) ~[hibernate-core-5.4.32.Final.jar:5.4.32.Final]
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
> 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
> 	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
> 	at org.hibernate.cfg.beanvalidation.BeanValidationIntegrator.integrate(BeanValidationIntegrator.java:131) ~[hibernate-core-5.4.32.Final.jar:5.4.32.Final]
> 	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:283) ~[hibernate-core-5.4.32.Final.jar:5.4.32.Final]
> 	at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:468) ~[hibernate-core-5.4.32.Final.jar:5.4.32.Final]
> 	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1259) ~[hibernate-core-5.4.32.Final.jar:5.4.32.Final]
> 	at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:58) ~[spring-orm-5.3.8.jar:5.3.8]
> ```
> 
> Adding this permission ("java.util.PropertyPermission" "org.hibernate.validator.force-disable-javafx-integration" "read")
> 
> or a wildcard "org.hibernate.*" should fix it.
> 
> Now, not a lot of tests are performed with the security manager enabled and lots of teams don't even bother to enable it ...
> 
> Hope this would help someone, one day!

Thank you so much for this comment, when I removed javafx from my pom, the error went away.

**Comment by ZhangErling** [comment]
> > 好的，所以这个问题不是无效的，也不是springboot相关的
> > 发生的情况是，当 hibernate 注册为 JPA 实现并且设置安全管理器时，该类 ValueExtractorManager 将不会被初始化，并且会导致一个奇怪的异常，该异常在类定义期间似乎永远不会被记录或触发/创建
> > ```
> > Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.hibernate.validator.internal.engine.valueextraction.ValueExtractorManager
> > 	at org.hibernate.validator.internal.engine.ValidatorFactoryImpl.<init>(ValidatorFactoryImpl.java:173) ~[hibernate-validator-6.2.0.Final.jar:6.2.0.Final]
> > 	at org.hibernate.validator.HibernateValidator.buildValidatorFactory(HibernateValidator.java:38) ~[hibernate-validator-6.2.0.Final.jar:6.2.0.Final]
> > 	at org.hibernate.validator.internal.engine.AbstractConfigurationImpl.buildValidatorFactory(AbstractConfigurationImpl.java:451) ~[hibernate-validator-6.2.0.Final.jar:6.2.0.Final]
> > 	at javax.validation.Validation.buildDefaultValidatorFactory(Validation.java:103) ~[jakarta.validation-api-2.0.2.jar:?]
> > 	at org.hibernate.cfg.beanvalidation.TypeSafeActivator.getValidatorFactory(TypeSafeActivator.java:502) ~[hibernate-core-5.4.32.Final.jar:5.4.32.Final]
> > 	at org.hibernate.cfg.beanvalidation.TypeSafeActivator.activate(TypeSafeActivator.java:84) ~[hibernate-core-5.4.32.Final.jar:5.4.32.Final]
> > 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
> > 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
> > 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
> > 	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
> > 	at org.hibernate.cfg.beanvalidation.BeanValidationIntegrator.integrate(BeanValidationIntegrator.java:131) ~[hibernate-core-5.4.32.Final.jar:5.4.32.Final]
> > 	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:283) ~[hibernate-core-5.4.32.Final.jar:5.4.32.Final]
> > 	at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:468) ~[hibernate-core-5.4.32.Final.jar:5.4.32.Final]
> > 	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1259) ~[hibernate-core-5.4.32.Final.jar:5.4.32.Final]
> > 	at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:58) ~[spring-orm-5.3.8.jar:5.3.8]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 添加此权限（“java.util.PropertyPermission”“org.hibernate.validator.force-disable-javafx-integration”“read”）
> > 或者通配符“org.hibernate.*”应该修复它。
> > 现在，在启用安全管理器的情况下执行的测试并不多，许多团队甚至懒得启用它......
> > 希望有一天这会对某人有所帮助！
> 
> 非常感谢您的评论，当我从我的 pom 中删除 javafx 时，错误就消失了。

是的，当我删除gs-ui-javafx时，我的错误也消失了，感谢提醒
