### ISSUE TITLE
Crashed when grails run-app recompiling

### ISSUE THREAD

**Issue by abcfy2** [AdoptOpenJDK/openjdk-support#92]
* **Platform and architecture (e.g. Linux/x64**: 

Linux/x64

* **Java version (from "java --version") e.g. 1.8.0_181, 11.0.4+11 etc.**:

```
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-b09)
Eclipse OpenJ9 VM (build openj9-0.20.0, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20200416_608 (JIT enabled, AOT enabled)
OpenJ9   - 05fa2d361
OMR      - d4365f371
JCL      - cfa47e66cd5 based on jdk8u252-b09)
```

* **Variant e.g. HotSpot or OpenJ9**:

OpenJ9

* **Have you tested it with other vendors' java**: Yes

* **Steps to reproduce**:

I don't know how to reproduce, but it seems only affect my project when `grails run-app` is recompiling:

```
File /home/fengyu/projects/jupiter/backend/grails-app/services/top/dteam/jupiter/backend/user/UserService.groovy changed, recompiling...
2020-04-24 01:18:58.424 DEBUG io.undertow.request                      : Timing out idle connection from /127.0.0.1:46052
Unhandled exception
Type=Segmentation error vmState=0x00000000
J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
Handler1=00007F0C45880E00 Handler2=00007F0C451729F0 InaccessibleAddress=0000000000000018
RDI=00007F0C2A3DF8C0 RSI=0000000000000001 RAX=0000000000000000 RBX=0000000000000001
RCX=0000000000000000 RDX=00007F0C29CCAB80 R8=0000000000000000 R9=00007F0C29CC1030
R10=0000000000000031 R11=00007F0C29CCB7D8 R12=0000000000000080 R13=0000000000000038
R14=00007F0C2A3DFD70 R15=00007F0C2A3DF8C0
RIP=00007F0C458FFF77 GS=0000 FS=0000 RSP=00007F0C2A3DF658
EFlags=0000000000010246 CS=0033 RBP=0000000000000001 ERR=0000000000000004
TRAPNO=000000000000000E OLDMASK=0000000000000000 CR2=0000000000000018
xmm0 2800562928005629 (f: 671110720.000000, d: 5.182657e-116)
xmm1 00ffffffffffffff (f: 4294967296.000000, d: 7.291122e-304)
xmm2 00736e6f69746174 (f: 1769234816.000000, d: 1.729451e-306)
xmm3 00736e6f69746174 (f: 1769234816.000000, d: 1.729451e-306)
xmm4 61566c61636f4c00 (f: 1668238336.000000, d: 7.881310e+160)
xmm5 02132712ea02b72a (f: 3926046464.000000, d: 1.143965e-298)
xmm6 570700a7dd02c000 (f: 3707944960.000000, d: 1.728720e+111)
xmm7 012b4cd802c01800 (f: 46143488.000000, d: 4.976222e-303)
xmm8 2a53cc02139b0213 (f: 328925728.000000, d: 8.631750e-105)
xmm9 0000000041040000 (f: 1090781184.000000, d: 5.389175e-315)
xmm10 2020202020202020 (f: 538976256.000000, d: 6.013470e-154)
xmm11 ffffffffffffffff (f: 4294967296.000000, d: -nan)
xmm12 0000000049ce7038 (f: 1238265856.000000, d: 6.117846e-315)
xmm13 000000004b010627 (f: 1258358272.000000, d: 6.217116e-315)
xmm14 000000004babca80 (f: 1269549696.000000, d: 6.272409e-315)
xmm15 000000004a096ed0 (f: 1242132224.000000, d: 6.136948e-315)
Module=/home/fengyu/.sdkman/candidates/java/8.0.252.j9-adpt/jre/lib/amd64/compressedrefs/libj9vm29.so
Module_base_address=00007F0C457EE000
Target=2_90_20200416_608 (Linux 5.4.34-1-MANJARO)
CPU=amd64 (4 logical CPUs) (0x1f191c000 RAM)
----------- Stack Backtrace -----------
(0x00007F0C458FFF77 [libj9vm29.so+0x111f77])
(0x00007F0C45905B64 [libj9vm29.so+0x117b64])
(0x00007F0C45905FF1 [libj9vm29.so+0x117ff1])
(0x00007F0C458E7BE0 [libj9vm29.so+0xf9be0])
(0x00007F0C458E9140 [libj9vm29.so+0xfb140])
(0x00007F0C458E9836 [libj9vm29.so+0xfb836])
(0x00007F0C458DE7B6 [libj9vm29.so+0xf07b6])
(0x00007F0C458DF5EE [libj9vm29.so+0xf15ee])
(0x00007F0C3E5CD035 [libjclse29.so+0x1c035])
Java_java_lang_ClassLoader_defineClassImpl+0x127 (0x00007F0C3E5C1897 [libjclse29.so+0x10897])
(0x00007F0C2B6B9E95 [<unknown>+0x0])
---------------------------------------
JVMDUMP039I 正在处理转储事件“gpf”，详细信息“”，位于 2020/04/24 01:19:01 - 请稍候。
JVMDUMP032I JVM 使用“/home/fengyu/projects/jupiter/backend/core.20200424.011901.132375.0001.dmp”来请求 System 转储以响应事件
JVMPORT030W /proc/sys/kernel/core_pattern 设置“|/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h”指定将核心转储输送到外部程序。正在尝试重命名 core 或 core.132523。

JVMDUMP012E System 转储中存在错误：The core file created by child process with pid = 132523 was not found. Expected to find core file with name "/home/fengyu/projects/jupiter/backend/core.132523"
JVMDUMP032I JVM 使用“/home/fengyu/projects/jupiter/backend/javacore.20200424.011901.132375.0002.txt”来请求 Java 转储以响应事件
JVMDUMP010I Java 转储已写入 /home/fengyu/projects/jupiter/backend/javacore.20200424.011901.132375.0002.txt
JVMDUMP032I JVM 使用“/home/fengyu/projects/jupiter/backend/Snap.20200424.011901.132375.0003.trc”来请求 Snap 转储以响应事件
JVMDUMP010I Snap 转储已写入 /home/fengyu/projects/jupiter/backend/Snap.20200424.011901.132375.0003.trc
JVMDUMP007I JVM 正使用“/home/fengyu/projects/jupiter/backend/jitdump.20200424.011901.132375.0004.dmp”请求 JIT 转储
JVMDUMP010I JIT 转储已写入 /home/fengyu/projects/jupiter/backend/jitdump.20200424.011901.132375.0004.dmp
JVMDUMP013I 已处理转储事件“gpf”，详细信息：“”。

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':bootRun'.
> Process 'command '/home/fengyu/.sdkman/candidates/java/8.0.252.j9-adpt/bin/java'' finished with non-zero exit value 255

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
| Error Failed to start server (Use --stacktrace to see the full trace)
```

And here is the dump files 
[dumps.zip](https://github.com/AdoptOpenJDK/openjdk-support/files/4524117/dumps.zip)

Please help. Thanks.

**Comment by DanHeidinga** [comment]
@abcfy2 Looking in the javacore from dumps.zip, I see that the bytecode verifier has been disabled:`  -Xverify:none`.  Does the problem still occur if you remove that option?

**Comment by DanHeidinga** [comment]
Crashing thread is defining a class at the time it crashes:
```
1XMCURTHDINFO  Current thread
3XMTHREADINFO      "FileSystemWatcher: files=#249 cl=sun.misc.Launcher$AppClassLoader@dcdae12d" J9VMThread:0x000000000017E600, omrthread_t:0x00007F0C401DE5B8, java/lang/Thread:0x00000000D00D3380, state:R, prio=5
3XMJAVALTHREAD            (java/lang/Thread getId:0x14, isDaemon:true)
3XMTHREADINFO1            (native thread ID:0x20530, native priority:0x5, native policy:UNKNOWN, vmstate:R, vm thread flags:0x00000020)
3XMTHREADINFO2            (native stack address range from:0x00007F0C2A3A4000, to:0x00007F0C2A3E4000, size:0x40000)
3XMCPUTIME               CPU usage total: 0.607327160 secs, current category="Application"
3XMHEAPALLOC             Heap bytes allocated since last GC cycle=36037104 (0x225E1F0)
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at java/lang/ClassLoader.defineClassImpl(Native Method)
4XESTACKTRACE                at java/lang/ClassLoader.defineClassInternal(ClassLoader.java:398(Compiled Code))
4XESTACKTRACE                at java/lang/ClassLoader.defineClass(ClassLoader.java:359(Compiled Code))
4XESTACKTRACE                at java/lang/ClassLoader.defineClass(ClassLoader.java:314)
4XESTACKTRACE                at org/springsource/loaded/ChildClassLoader.defineClass(ChildClassLoader.java:39)
4XESTACKTRACE                at org/springsource/loaded/TypeRegistry.defineClass(TypeRegistry.java:1306(Compiled Code))
4XESTACKTRACE                at org/springsource/loaded/CurrentLiveVersion.define(CurrentLiveVersion.java:137)
4XESTACKTRACE                at org/springsource/loaded/CurrentLiveVersion.<init>(CurrentLiveVersion.java:111)
4XESTACKTRACE                at org/springsource/loaded/ReloadableType.loadNewVersion(ReloadableType.java:422)
4XESTACKTRACE                at org/springsource/loaded/TypeRegistry.loadNewVersion(TypeRegistry.java:1018)
4XESTACKTRACE                at org/springsource/loaded/agent/ReloadableFileChangeListener.fileChanged(ReloadableFileChangeListener.java:104)
4XESTACKTRACE                at org/springsource/loaded/agent/Watcher.determineChangesSince(FileSystemWatcher.java:251)
4XESTACKTRACE                at org/springsource/loaded/agent/Watcher.run(FileSystemWatcher.java:235)
4XESTACKTRACE                at java/lang/Thread.run(Thread.java:821)
```
I think the verifier will reject the class with a java.lang.VerifyError once the `-Xverify:none` option is removed.

**Comment by abcfy2** [comment]
It seems that this option was add by grails or gradle by default, I can't modify it.

```bash
./grailsw run-app

# open another terminal
ps aux | grep java
fengyu      7875  136  5.7 2903736 468964 ?      SLl  10:00   0:28 /home/fengyu/.sdkman/candidates/java/8.0.252.j9-adpt/bin/java -Dendpoints.shutdown.enabled=true -Denv=development -Dfull.stacktrace=false -Dgrails.env=development -Dgrails.full.stacktrace=false -Dinfo.app.grailsVersion=3.3.6 -Dinfo.app.name=backend -Dinfo.app.version=0.1 -Djdk.reflect.allowGetCallerClass=true -Drun.active=true -Dserver.port=9002 -Dspring.output.ansi.enabled=always -Dspring.profiles.active -Dspringloaded=inclusions=grails.plugins..*;synchronize=true;allowSplitPackages=true;cacheDir=/home/fengyu/projects/jupiter/backend/build/springloaded -Dverbose=false -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -XX:CICompilerCount=3 -javaagent:/home/fengyu/.gradle/caches/modules-2/files-2.1/org.springframework/springloaded/1.2.8.RELEASE/b60bac05b0451cdc1863bfec617f39aa0dcaaa43/springloaded-1.2.8.RELEASE.jar -Xverify:none -Xms768m -Xmx768m -Dfile.encoding=UTF-8 -Duser.country=CN -Duser.language=zh -Duser.variant -cp
# ...SNIP...
# You can see the command contains  -Xverify:none -Xms768m -Xmx768m -Dfile.encoding=UTF-8 -Duser.country=CN -Duser.language=zh -Duser.variant
```

**Comment by abcfy2** [comment]
I searched the source code from grails, and I find this: https://github.com/grails/grails-core/blob/master/grails-gradle-plugin/src/main/groovy/org/grails/gradle/plugin/core/GrailsExtension.groovy#L79

Grails added `-Xverify:none` by default.

**Comment by abcfy2** [comment]
It seems that `-Xverify:none` cannot be removed. I try to download `grails-3.3.6` source code: https://github.com/grails/grails-core/archive/v3.3.6.tar.gz

Modified source code `grails-gradle-plugin/src/main/groovy/org/grails/gradle/plugin/core/GrailsExtension.groovy` change `List<String> jvmArgs = ['-Xverify:none']` to `List<String> jvmArgs = []`

Then use `./gradlew publishToMavenLocal` to publish to `mavenLocal()`

Modify `build.gradle` in my project:

```groovy
buildscript {
    repositories {
        mavenLocal()   // add this
        maven { url "https://repo.grails.org/grails/core" }
    }
// ... SNIP ...
}

repositories {
    mavenLocal()  // and this
    maven { url "https://repo.grails.org/grails/core" }
}
```

Then use `./gradlew bootrun` or `./grailsw run-app` to run my project.

But I get this error:

```
LC_ALL=en_US.UTF-8 ./gradlew bootrun
:compileJava NO-SOURCE
:compileGroovy UP-TO-DATE
:generateGitProperties UP-TO-DATE
:buildProperties UP-TO-DATE
:processResources
:classes
:findMainClass
:bootRunError: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.VerifyError: JVMVRFY012 stack shape inconsistent; class=grails/boot/config/GrailsAutoConfiguration, method=<clinit>()V, pc=0
Exception Details:
  Location:
    grails/boot/config/GrailsAutoConfiguration.<clinit>()V @0: JBldc
  Reason:
    A stackmap frame is expected at branch target 65.
  Exception Handler Table:
    bci [0, 65] => handler: 65
    bci [0, 65] => handler: 74
    bci [65, 67] => handler: 74
        at java.lang.J9VMInternals.prepareClassImpl(Native Method)
        at java.lang.J9VMInternals.prepare(J9VMInternals.java:304)
        at java.lang.Class.getMethodHelper(Class.java:1247)
        at java.lang.Class.getMethod(Class.java:1191)
        at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':bootRun'.
> Process 'command '/home/fengyu/.sdkman/candidates/java/8.0.252.j9-adpt/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 8.133 secs
```

And rollback the `GrailsExtension.groovy` then publish to maven local again could run app.

**Comment by DanHeidinga** [comment]
A crash at runtime isn't surprising given that unverifiable code is being generated.  The JVM in general, and OpenJ9 specifically, rely on the verifier to ensure that the code being run is valid.  When code can't be verified, any number of invariants in the VM are broken and may result in strange behaviour or crashes.

I've opened https://github.com/grails/grails-core/issues/11528 in the grails community to let them know of the issue as it will need to be fixed by grails.  We can't support unverifiable bytecode.

@abcfy2 any details you can add to the grails issue would be appreciated
